sitesatis/Controllers/MenuController.cs
using NPOI.HSSF.UserModel;
using NPOI.HSSF.Util;
using NPOI.SS.UserModel;
using NPOI.SS.Util;
using sitesatis.business.helper;
using sitesatis.Models.entity;
using sitesatis.Models.repository.abstracti;
using sitesatis.Models.repository.manager;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sitesatis.Controllers
{
    public class MenuController : Controller
    {
        menumanager menum = new menumanager();
        menuview mv = new menuview();
        // GET: category


        public ActionResult Index(int? id)
        {
            int page;
            if (id != null)
            {
                page = id.Value;
            }
            else
            { page = 0; }

            mv._Menu = menum.read().Skip(page).Take(10).ToList();//.Skip(page).ToList();
            mv.pagelist1 = mv._Menu.Count() / 10;

            return View(mv);
        }



        // POST: Product/Create
        public ActionResult create()
        {
            mv._Menu = menum.read();
            return View(mv);
        }
        public ActionResult tara()
        {
            var td = filehelper.sitepagecreate(Server.MapPath("~/Views/"),new sitepage { });
            return View(td);
        }

        [HttpPost]
        public ActionResult Create(menu _menu)
        {

            try
            {
                menum.create(new menu
                {
                    menu_link_name = _menu.menu_link_name,
                    sitepage = _menu.sitepage
                });
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Edit(menu _menu)
        {

            menum.update(new menu
            {
                menu_link_name = _menu.menu_link_name,
                sitepage = _menu.sitepage
            });
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            try
            {
                mv._Menu = menum.read();
                return View(mv);
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }


        public ActionResult Delete(int id)
        {
            try
            {
                menum.delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
    public class menuview
    {
        public IEnumerable<menu> _Menu { get; set; }
        public menu _menu { get; set; }
        public int pagelist1 { get; set; }
    }

}

sitesatis/Controllers/ProductController.cs
using NPOI.HSSF.UserModel;
using NPOI.HSSF.Util;
using NPOI.SS.UserModel;
using NPOI.SS.Util;
using sitesatis.business.NPOI;
using sitesatis.business.rolemanager;
using sitesatis.Models.attribute;
using sitesatis.Models.entity;
using sitesatis.Models.repository.manager;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sitesatis.Controllers
{
    public class ProductController : Controller
    {
        productmanager pm = new productmanager();
        productview pv = new productview();
        categorymanager cm = new categorymanager();
        cargotypemanager ctm = new cargotypemanager();
        cargomanager carm = new cargomanager();
        repositorymanager rm = new repositorymanager();
        // GET: category

        
        public ActionResult Index(int? id)
        {
            int page;
            if(id != null)
            {
                page = id.Value;
            }
            else
            { page = 0; }

            pv.product = pm.read().Skip(page).Take(10).ToList();//.Skip(page).ToList();
            pv.pagelist = pv.product.Count() / 10;

            return View(pv);
        }

        public FileResult excel()
        {
            IWorkbook workbook = new HSSFWorkbook(); //döküman
            ISheet sheet1 = workbook.CreateSheet("product 12"); //sayfa

            productmanager pm = new productmanager();//

            var style =  workbook.CreateCellStyle();//sitil dosyası
            style.FillForegroundColor = HSSFColor.Blue.Index2; //renk
            style.Alignment = HorizontalAlignment.Center;// metin hizalama
            style.VerticalAlignment = VerticalAlignment.Center;//metin hzalama
            style.FillPattern = FillPattern.SolidForeground;// renk doldurma

            sheet1.AddMergedRegion(new CellRangeAddress(0, 1, 0, 9));//birleştirme
            var rowIndex = 0;
            var row = sheet1.CreateRow(rowIndex).CreateCell(0);
            row.CellStyle = style;
            row.SetCellValue("deneme son vol:3");

            rowIndex+=2;
            foreach(var item in pm.read())
            {
                var row1 = sheet1.CreateRow(rowIndex);
                row1.CreateCell(0).SetCellValue(item.product_name);//hücre değerleri
                sheet1.AutoSizeColumn(0);// hücre veriye göre boyutlandırma
                row1.CreateCell(1).SetCellValue(item.cargo.cargo_company);
                sheet1.AutoSizeColumn(1);
                row1.CreateCell(2).SetCellValue(item.category.category_name);
                sheet1.AutoSizeColumn(8);
                row1.CreateCell(3).SetCellValue(item.cargo_type.cargo_type1);
                sheet1.AutoSizeColumn(2);
                row1.CreateCell(4).SetCellValue(item.product_content);
                sheet1.AutoSizeColumn(3);
                row1.CreateCell(5).SetCellValue(item.product_add_time.ToString());
                sheet1.AutoSizeColumn(4);
                row1.CreateCell(6).SetCellValue(item.product_price.ToString());
                sheet1.AutoSizeColumn(5);
                row1.CreateCell(7).SetCellValue(item.product_quantity.ToString());
                sheet1.AutoSizeColumn(6);
                row1.CreateCell(8).SetCellValue(item.prouct_image_path);
                sheet1.AutoSizeColumn(7);
                row1.CreateCell(9).SetCellValue(item.repository.repository_name);
                sheet1.AutoSizeColumn(9);
                rowIndex++;

            }
            var stream = new MemoryStream();
            workbook.Write(stream);

            return File(new MemoryStream(stream.GetBuffer()), "application/vdn.ms-excel", "producttable.xls");

        }
        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // POST: Product/Create
        public ActionResult create()
        {
            pv.category = cm.read();
            pv.cargotype = ctm.read();
            pv.repository = rm.read();
            pv.cargo = carm.read();
            return View(pv);
        }

        [HttpPost]
        public ActionResult Create(product _product,HttpPostedFileBase prouct_image_path)
        {
            if(prouct_image_path != null)
            {
                string dosyaYolu = Path.GetFileName(prouct_image_path.FileName);
                var yuklemeYeri = Path.Combine(Server.MapPath("~/image/"), dosyaYolu);
                prouct_image_path.SaveAs(yuklemeYeri);
                _product.prouct_image_path = prouct_image_path.FileName;
            }
            try
            {
                pm.create(new product
                {
                    product_name = _product.product_name,
                    product_content = _product.product_content,
                    category_id = _product.category_id,
                    cargo_type_id = _product.cargo_type_id,
                    cargo_id = _product.cargo_type_id,
                    product_price = _product.product_price,
                    prouct_image_path = _product.prouct_image_path.ToString(),
                    publisher = 1,
                    product_quantity = _product.product_quantity,
                    repository_id = _product.repository_id,
                    product_add_time = DateTime.Now
                });
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Edit(product _product, HttpPostedFileBase prouct_image_path)
        {
            if(prouct_image_path != null)
            {
                string dosyaYolu = Path.GetFileName(prouct_image_path.FileName);
                var yuklemeYeri = Path.Combine(Server.MapPath("~/image/"), dosyaYolu);
                prouct_image_path.SaveAs(yuklemeYeri);
                _product.prouct_image_path = prouct_image_path.FileName;
            }
            pm.update(new product {
                id = _product.id,
                product_name = _product.product_name,
                product_content = _product.product_content,
                category_id = _product.category_id,
                cargo_type_id = _product.cargo_type_id,
                cargo_id = _product.cargo_type_id,
                product_price = _product.product_price,
                prouct_image_path = _product.prouct_image_path,
                publisher = 1,
                product_quantity = _product.product_quantity,
                repository_id = _product.repository_id,
                product_add_time = DateTime.Now
            });
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            try
            {
                pv.cargo = carm.read();
                pv.cargotype = ctm.read();
                pv._product = pm.filterread(x=>x.id == id);
                pv.repository = rm.read();
                pv.product = pm.read();
                pv.category = cm.read();
                return View(pv);
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }


        public ActionResult Delete(int id)
        {
            try
            {
                pm.delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
    public class productview
    {
        public IEnumerable<product> product { get; set; }
        public IEnumerable<category> category { get; set; }
        public IEnumerable<cargo_type> cargotype { get; set; }
        public IEnumerable<cargo> cargo { get; set; }
        public IEnumerable<repository> repository { get; set; }
        public product _product { get; set; }
        public int pagelist { get; set; }
    }

}

sitesatis/Controllers/ShoppingCartController.cs
using sitesatis.Models.entity;
using sitesatis.Models.repository.manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sitesatis.Controllers
{
    public class ShoppingCartController : Controller
    {
        menumanager menum = new menumanager();
        shopcartmodel shopm = new shopcartmodel();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            shopm.menu = menum.read();
            return View(shopm);
        }
    }
    public class shopcartmodel
    {
        public IEnumerable<Models.entity.menu> menu { get; set; }
    }
}

sitesatis/Views/Shared/_Layout.cshtml
@model sitesatis.Controllers.homeviewmodel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="container-fluid ">
        @* menu *@
        <div class="row pt-2" style="background-color:#f2f1e9;">
            <div class="col-lg-12">
                <div class="container">
                    <div class="row p-1">
                        <div class="col-lg-1 p-2 ">
                            <img src="~/image/cart.png" />
                        </div>
                        <div class="col-lg-8 pt-3">
                            <div class="search-container">
                                <form action="~/Home/search/" >
                                    <div class="container-fluid">
                                        <div class="row">
                                            <div class="col-11  p-0">
                                                <input type="text" placeholder="Search.." name="search">
                                            </div>
                                            <div class="col-1 p-0">
                                                <button type="submit"><i class="fa fa-search"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </form>
                            </div>
                        </div>
                        <div class="col-lg-2 pt-3">
                            
                            <nav class="navbar navbar-expand-lg navbar-light font-weight-bold">

                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarNav">
                                    <ul class="navbar-nav">
                                        @foreach(var item in Model.homemenu)
                                        {
                                            <li class="nav-item active">
                                                <a class="nav-link" href="~/@item.sitepage.site_control/@item.sitepage.site_link ">@item.sitepage.site_name</a>
                                            </li>
                                        }

                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @* banner *@
        <div class="row" style="background-image:url('https://www.kaft.com/static/images/content/banner/500_TR.jpg?1568618994000'); background-size:cover; background-attachment:local;background-position:center; height:50vh;">    
        </div>
        @* left navbar  *@
        <div class="row d-flex justify-content-center">
            <div class="col-lg-11 ">
                <div class="container-fluid">
                    <div class="row d-flex justify-content-center">
                        <div class="col-lg-3 ">
                            <div class="container-fluid">
                                <div class="row d-flex justify-content-center">

                                    <div class="col-12 pt-2 menu ">
                                        <div class="col-12 pt-2 bg-dark text-light font-weight-bold text-uppercase" style="font-size:15pt;">
                                            kategori
                                        </div>
                                        <ul>
                                            @foreach (var category in Model.homecategoriy)
                                            {
                                                <li><a href="~/Home/filtre/@category.id">@category.category_name</a></li>
                                            }
                                        </ul>
                                    </div>
                                </div>
                                @*<div class="row mt-5 d-flex justify-content-center">

                                    <div class="col-12 pt-2 menu ">
                                        <div class="col-12 pt-2 bg-dark text-light font-weight-bold text-uppercase" style="font-size:15pt;">
                                            filtre
                                        </div>
                                        <ul>
                                            <li><a href="~/Home/cinsiyet/erkek">erkek</a></li>
                                            <li><a href="~/Home/cinsiyet/kadin">kadın</a></li>
                                        </ul>
                                    </div>
                                </div>*@
                            </div>
                        </div>
                        <div class="col-lg-9  ">
                            <div class="container-fluid bg-dark mt-2">
                                <div class="row pt-2">
                                    <div class="col-12 pt-3 mt-2 bg-light pb-5">
                                        @RenderBody()
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row bg-dark pt-5">
            <div class="col-11 text-center text-light">
                &copy; copyright göksel kalyon
                <br />
                <br />
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

sitesatis/Views/Shared/_LoginPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        #bodylogin {
            background-image: url(/image/bg-01.jpg);
            background-attachment:fixed;
            background-position: center;
            background-size:cover;
        }
    </style>
</head>
<body id="bodylogin">
    <div class="container-fluid" id="bodylogin">
        @RenderBody()
    </div>
</body>
</html>

sitesatis/Views/Shared/_ProfilLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">

    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-6 p-4 bg-dark rounded">
                <form class="needs-validation" method="post" novalidate>
                    <div class="form-row">
                        <div class="col-md-12 mb-3">
                            <label for="validationTooltip01">ürün adı</label>
                            <input type="text" class="form-control" name="product_name" value="Model._product.product_name.ToString()" id="validationTooltip01" placeholder="ürün adı" required>
                            <div class="valid-tooltip">
                                iyi
                            </div>
                        </div>

                        <div class="col-md-12 mb-3">
                            <label for="validationTooltip02">ürün açıklaması</label>
                            <input type="text" class="form-control" name="product_content" value="Model._product.product_content" id="validationTooltip02" placeholder="ürün açıklaması" required>
                            <div class="valid-tooltip">
                                iyi
                            </div>
                        </div>
                        <div class="col-md-12 mb-3">
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">kategori</label>
                                <select class="form-control" name="category_id" id="exampleFormControlSelect1">
                                 <option value="category.id">category.category_name</option>
                                    

                                </select>
                            </div>
                        </div>
                        <div class="col-md-12 mb-3">
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">kargo tipi</label>
                                <select class="form-control" name="cargo_type_id" id="exampleFormControlSelect1">
                                    <option value="cargotype.id">cargotype.cargo_type1 </option>
                                  
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12 mb-3">
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">kargo şirketi</label>
                                <select class="form-control" name="cargo_id" id="exampleFormControlSelect1">
                                    <option value="cargo.id">cargo.cargo_company </option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="validationTooltip05">ürün fiyatı</label>
                            <input type="number" name="product_price" value="Model._product.product_price" class="form-control" id="validationTooltip05" placeholder="fiyat" required>
                            <div class="invalid-tooltip">
                            </div>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="validationTooltip05">ürün resmi</label>

                            <div class="custom-file">
                                <input type="file" name="prouct_image_path" value="Model._product.prouct_image_path" class="custom-file-input" id="customFileLang" lang="es">
                                <label class="custom-file-label" for="customFileLang">Seleccionar Archivo</label>
                            </div>
                        </div>
                        @* publisher'ı eklettirmeyi unutturma *@
                        <div class="col-md-12 mb-3">
                            <label for="validationTooltip05">ürün adeti</label>
                            <input type="number" name="product_quantity" value="Model._product.product_quantity" class="form-control" id="validationTooltip05" placeholder="adet" required>
                            <div class="invalid-tooltip">
                            </div>
                        </div>
                        <div class="col-md-12 mb-3">
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">bulunduğu depo</label>
                                <select class="form-control" name="repository_id" id="exampleFormControlSelect1">
                                  
                                        <option value="repository.id">repository.repository_name </option>
                                   

                                </select>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">ürünü ekle</button>
                </form>
                @RenderBody();
            </div>
        </div>
    </div>
</body>
</html>

sitesatis/Views/Shared/_adminpanel.cshtml
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="~/asset/images/favicon.png" />
    <title>admin panel</title>
    <!-- Custom CSS -->
    <link href="~/asset/libs/flot/css/float-chart.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/dist/css/style.min.css" rel="stylesheet" />

    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

</head>

<body>
   
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin5">
                    <!-- This is for the sidebar toggle which is visible on mobile only -->
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                    
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav float-left mr-auto">
                        <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                        
                        <!-- ============================================================== -->
                        <!-- Search -->
                        <!-- ============================================================== -->
                        <li class="nav-item search-box">
                            <a class="nav-link waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <form class="app-search position-absolute">
                                <input type="text" class="form-control" placeholder="Search &amp; enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                            </form>
                        </li>
                    </ul>
                    
                </div>

            </nav>
        </header>
        <aside class="left-sidebar" data-sidebarbg="skin5">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">
                        <li class="sidebar-item"><a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Index","Product")" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Ürünler</span></a></li>
                        <li class="sidebar-item"><a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Index","Category")" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Kategori</span></a></li>
                        <li class="sidebar-item"><a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Index","Menu")" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Menu</span></a></li>

                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
  
        <div class="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <footer class="footer text-center">
                All Rights &copy; copyright göksel kalyon.
            </footer>
           
        </div>
       
    </div>
    
    <script src="~/asset/libs/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/asset/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/asset/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="~/asset/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/dist/js/custom.min.js"></script>
    

</body>

</html>